version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: kingmaxud/nestapp:1.0.0
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=postgres
      - PG_HOST=db
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DATABASE=postgres
      - PG_PORT=5432
      - JWT_ACCESS_TOKEN_SECRET=p3aeAde3/lIUFR4+vZWkYZyfrru5E4DyvdgOmR2JBJmnvjt91GMfKrc2YaJVWHdxn2oSPePTP8LK/YNphS5PKgdjwrymLwC+DxE4AmIGL/eOxAbRNLPukGpUDDHj3Sg+
      - JWT_ACCESS_TOKEN_EXPIRATION_TIME=180
      - JWT_REFRESH_TOKEN_SECRET=zRLorKrD1gmD8FvD+0Trv4vXcTsvk3jAy+wFCEp5LpfqQZnFV0GVdDKBlwAT/qt5PPPZVM3Mo9VkFfuEYiNL3ZzfYIXpUn/mrvtuZgucQ6BnVBHldVMjZcIfTlj8HuI7
      - JWT_REFRESH_TOKEN_EXPIRATION_TIME=259200
    depends_on:
      - db

  db:
    container_name: db
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
